services:
  app:
    build:
      context: .
    container_name: app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    # The app service runs Django with Gunicorn by default (see Dockerfile)

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: skylearn
      POSTGRES_USER: skylearn
      POSTGRES_PASSWORD: skylearn
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skylearn"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    # Default Postgres port is not exposed to host for security; app connects via network

networks:
  backend:
    driver: bridge

volumes:
  db_data:
    # Persistent storage for PostgreSQL
